# Generated by Django 3.2.18 on 2023-02-16 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0004_auto_20160409_2334"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={
                "ordering": ["domain"],
                "verbose_name": "site",
                "verbose_name_plural": "sites",
            },
        ),
    ]
