# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-15 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20150503_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='alarm',
        ),
    ]
