# Generated by Django 2.2.9 on 2020-02-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0011_letter_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='message',
        ),
    ]
