# Generated by Django 2.2.25 on 2021-12-30 10:46

from django.db import migrations, models


def migrate_created_by_staff(apps, schema_editor):
    User = apps.get_model("users", "User")
    Letter = apps.get_model("letters", "Letter")
    Letter.objects.filter(created_by__in=User.objects.filter(is_staff=True)).update(
        created_by_staff=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0011_letter_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="created_by_staff",
            field=models.BooleanField(
                default=False, verbose_name="Created by staff member"
            ),
        ),
        migrations.RunPython(migrate_created_by_staff),
    ]
