# Generated by Django 2.2.25 on 2021-12-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0012_letter_created_by_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="created_by_is_staff",
            field=models.BooleanField(verbose_name="Created by staff member"),
        ),
    ]
