# Generated by Django 2.2.25 on 2021-12-30 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0012_update_letter_genre"),
        ("letters", "0013_auto_20211230_1439"),
    ]

    operations = []
