# Generated by Django 4.2.11 on 2024-03-22 15:31

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0016_alter_letter_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=model_utils.fields.StatusField(choices=[('staff', 'Staff'), ('done', 'Done')], db_index=True, default='staff', max_length=100, no_check_for_status=True),
        ),
    ]
