# Generated by Django 5.2.10 on 2026-01-14 15:37

from django.db import migrations, models

import poradnia.letters.utils


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0017_alter_letter_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="attachment",
            field=models.FileField(
                max_length=500,
                upload_to=poradnia.letters.utils.date_random_path,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Subject"),
        ),
    ]
