# Generated by Django 5.2.15 on 2026-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0019_attachment_text_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="genre",
            field=models.CharField(
                choices=[
                    ("mail", "mail"),
                    ("comment", "comment"),
                    ("app_message", "app_message"),
                    ("ai_message", "ai_message"),
                    ("ai_message_staff", "ai_message_staff"),
                ],
                default="comment",
                max_length=20,
            ),
        ),
    ]
