# Generated by Django 5.2.16 on 2026-08-11 12:43
# Manually edited: replaced the bare RemoveField with a
# SeparateDatabaseAndState that checks whether `message_id` still exists
# before dropping it. On tables with real data this DROP COLUMN needs a
# full table rebuild (the column carries an FK + index), and MySQL commits
# DDL independently of Django's migration transaction. If the connection is
# lost after the ALTER TABLE commits but before Django records the
# migration as applied, a retry used to hit MySQLdb.OperationalError 1091
# ("Can't DROP 'message_id'; check that column/key exists") forever. This
# makes the operation idempotent: a retry that finds the column already
# gone just no-ops and lets the migration complete.

from django.db import migrations


def drop_message_column_if_exists(apps, schema_editor):
    table = "letters_letter"
    column = "message_id"

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.columns "
            "WHERE table_schema = DATABASE() AND table_name = %s "
            "AND column_name = %s",
            [table, column],
        )
        if not cursor.fetchone()[0]:
            return

        cursor.execute(
            "SELECT constraint_name FROM information_schema.key_column_usage "
            "WHERE table_schema = DATABASE() AND table_name = %s "
            "AND column_name = %s AND referenced_table_name IS NOT NULL",
            [table, column],
        )
        fk_names = [row[0] for row in cursor.fetchall()]

        for fk_name in fk_names:
            cursor.execute(f"ALTER TABLE `{table}` DROP FOREIGN KEY `{fk_name}`")
        cursor.execute(f"ALTER TABLE `{table}` DROP COLUMN `{column}`")


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0020_alter_letter_genre"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="letter",
                    name="message",
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    drop_message_column_if_exists, migrations.RunPython.noop
                ),
            ],
        ),
    ]
