# Generated by Django 5.2.16 on 2026-08-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0020_alter_letter_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='message',
        ),
    ]
