FROM node:19
WORKDIR /app
VOLUME /app
CMD ["bash","-c", "npm install && npm rebuild node-sass && npx gulp build"]
#CMD ["bash","-c", " npm install ; npm rebuild node-sass ; npx gulp build ;sleep infinity "]
