# This is Dockerfile for development purposes only.
ARG PYTHON_VERSION='3.10'
FROM python:${PYTHON_VERSION}-slim
RUN mkdir /code /code/production
WORKDIR /code

# Install python dependencies
ENV PYTHONUNBUFFERED 1
RUN apt-get update \
&& apt-get install -y --no-install-recommends \
   python3-dev default-libmysqlclient-dev build-essential \
   default-mysql-client libssl-dev pkg-config \
   gcc \
   git \
   curl \
   nano \
   htop \
   gettext libgettextpo-dev wait-for-it
COPY requirements/*.txt ./requirements/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements/dev.txt
# CMD ["bash", "-c", "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
# Chended to allow VScode run and debug django app or debug container starting errors:
CMD ["bash", "-c", "python manage.py collectstatic --no-input ; python manage.py migrate ; sleep infinity "]
