# This is Dockerfile for development purposes only.
ARG PYTHON_VERSION='2'
FROM python:${PYTHON_VERSION}-slim
RUN mkdir /code /code/production
WORKDIR /code

# Install python dependencies
ENV PYTHONUNBUFFERED 1
RUN apt-get update \
&& apt-get install -y --no-install-recommends \
   default-libmysqlclient-dev \
   gcc \
   build-essential \
   git \
   curl \
&& rm -rf /var/lib/apt/lists/*
COPY requirements/*.txt ./requirements/
ARG DJANGO_VERSION='==1.11.21'
RUN pip install --no-cache-dir -r requirements/dev.txt "django${DJANGO_VERSION}"
CMD ["bash", "-c", "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
