# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_squashed_0007_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
    ]
