# Generated by Django 1.11.8 on 2018-04-15 17:23
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("events", "0009_auto_20180415_1922")]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="active",
            field=models.BooleanField(default=True, help_text="Active status"),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="user",
            field=models.ForeignKey(
                help_text="Recipient",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
