# Generated by Django 3.2.18 on 2023-04-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_event_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Event is visible to customers (ext).",
                verbose_name="Public",
            ),
        ),
    ]
