# Generated by Django 1.11.4 on 2017-08-27 08:55
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0014_auto_20170317_1927")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_footer",
            field=models.TextField(blank=True, null=True, verbose_name="Email footer"),
        )
    ]
