# Generated by Django 1.10.7 on 2017-09-29 04:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0015_profile_email_footer")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_new_case",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not to notify user about all new cases",
                verbose_name="Notify about new case",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_unassigned_letter",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not to notify user about any letter in free cases",
                verbose_name="Notify about letter in free cases",
            ),
        ),
    ]
