# Generated by Django 2.2.25 on 2022-01-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_auto_20191015_0510"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notify_unassigned_letter",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not to notify user about any letter in case without anybody who can reply to client",
                verbose_name="Defaults to reply in cases",
            ),
        ),
    ]
