# Generated by Django 3.2.18 on 2023-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_old_cases",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not to notify user about all cases",
                verbose_name="Notify about old cases",
            ),
        ),
    ]
