# Generated by Django 3.2.18 on 2023-04-26 14:50

from django.db import migrations, models


def update_nicename(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.nicename = (
            " ".join([user.first_name, user.last_name]).strip() or user.username
        )
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_user_notify_old_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nicename",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Nice Name"
            ),
        ),
        migrations.RunPython(update_nicename),
    ]
