# Generated by Django 3.2.18 on 2023-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_user_nicename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notify_old_cases",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not to notify user about old cases",
                verbose_name="Notify about old cases",
            ),
        ),
    ]
