# Generated by Django 3.2.24 on 2024-02-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_user_notify_old_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_content_editor",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not to show user tinycontent editable fields",
                verbose_name="Content Editor",
            ),
        ),
    ]
