# Generated by Django 5.2.11 on 2026-02-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_user_is_content_editor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
