
# Generated by Django 1.11.8 on 2018-04-20 16:18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgements', '0001_squashed_0003_auto_20180416_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtsession',
            name='parser_key',
            field=models.CharField(max_length=25, verbose_name='Parser key'),
        ),
    ]
