# Generated by Django 1.11.8 on 2018-04-15 23:31
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("judgements", "0002_auto_20180415_2330")]

    operations = [
        migrations.RenameField(
            model_name="courtsession", old_name="court_case", new_name="courtcase"
        ),
        migrations.AddField(
            model_name="courtsession",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="courtsession",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="courtsession",
            name="parser_key",
            field=models.CharField(
                default="", max_length=25, verbose_name="Parser key"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="courtcase",
            name="signature",
            field=models.CharField(help_text="Court signature", max_length=50),
        ),
        migrations.AlterField(
            model_name="courtsession",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.Event",
                verbose_name="Event",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courtcase", unique_together={("court", "signature")}
        ),
    ]
