# Generated by Django 5.2.15 on 2026-06-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0044_case_advice_classification_request_sent_on_and_more"),
        ("letters", "0020_alter_letter_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="N8nArticlesSearchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=100, unique=True)),
                ("environment", models.CharField(max_length=10)),
                ("question", models.TextField()),
                ("direct_search", models.BooleanField(default=False)),
                ("response", models.TextField(blank=True)),
                ("is_foi", models.CharField(blank=True, max_length=3)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_search_requests",
                        to="cases.case",
                    ),
                ),
                (
                    "letter",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_search_request",
                        to="letters.letter",
                    ),
                ),
            ],
        ),
    ]
