# Generated by Django 5.2.15 on 2026-06-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="n8narticlessearchrequest",
            name="letter",
        ),
    ]
