# Generated by Django 5.2.15 on 2026-07-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_remove_n8narticlessearchrequest_letter'),
        ('cases', '0044_case_advice_classification_request_sent_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='N8nCaseTagsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('environment', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tags_requests', to='cases.case')),
            ],
        ),
    ]
