# Generated by Django 2.2.12 on 2020-04-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasty_feedback", "0003_auto_20180104_0436"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="url",
            field=models.CharField(default="", help_text="URL", max_length=300),
            preserve_default=False,
        ),
    ]
