# Generated by Django 4.2.16 on 2024-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasty_feedback', '0004_feedback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(help_text='Text reported by user', verbose_name='Content'),
        ),
    ]
