# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import model_utils.fields


class Migration(migrations.Migration):

    replaces = [(b'cases', '0002_auto_20150102_1532'), (b'cases', '0003_auto_20150103_0643'), (b'cases', '0004_auto_20150304_1650'), (b'cases', '0005_auto_20150305_0755'), (b'cases', '0006_auto_20150307_1849'), (b'cases', '0007_auto_20150307_1854'), (b'cases', '0008_auto_20150308_0657'), (b'cases', '0009_auto_20150308_0738'), (b'cases', '0010_auto_20150308_0917'), (b'cases', '0011_auto_20150310_0159'), (b'cases', '0012_auto_20150311_0434'), (b'cases', '0013_auto_20150312_2326'), (b'cases', '0014_auto_20150312_2338'), (b'cases', '0015_auto_20150312_2340'), (b'cases', '0016_auto_20150316_0931'), (b'cases', '0017_case_deadline'), (b'cases', '0018_auto_20150428_0733'), (b'cases', '0019_auto_20150503_1741'), (b'cases', '0020_permissiongroup')]

    dependencies = [
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
        ('events', '0004_auto_20150322_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': (('can_view_all', 'Can view all cases'), ('can_view', 'Can view'))},
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default=b'free', max_length=100, no_check_for_status=True),
        ),
        migrations.CreateModel(
            name='CaseGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='caseuserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='casegroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object')]),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': (('can_view_all', 'Can view all cases'), ('can_view', 'Can view'), ('can_select_client', 'Can select client'), ('can_assign', 'Can assign new permissions'), ('can_send_to_client', 'Can send text to client'))},
        ),
        migrations.AddField(
            model_name='case',
            name='last_action',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 3, 8, 2, 49, 55, 496358, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='letter_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['last_action'], 'permissions': (('can_view_all', 'Can view all cases'), ('can_view', 'Can view'), ('can_select_client', 'Can select client'), ('can_assign', 'Can assign new permissions'), ('can_send_to_client', 'Can send text to client'))},
        ),
        migrations.AlterField(
            model_name='case',
            name='last_action',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['last_action'], 'permissions': (('can_view_all', 'Can view all cases'), ('can_view', 'Can view'), ('can_select_client', 'Can select client'), ('can_assign', 'Can assign new permissions'), ('can_send_to_client', 'Can send text to client'), ('can_manage_permission', 'Can assign permission'), ('can_change_own_record', 'Can change own records'), ('can_change_all_record', 'Can change all records'))},
        ),
        migrations.AlterField(
            model_name='case',
            name='last_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['last_send'], 'permissions': (('can_view_all', 'Can view all cases'), ('can_view', 'Can view'), ('can_select_client', 'Can select client'), ('can_assign', 'Can assign new permissions'), ('can_send_to_client', 'Can send text to client'), ('can_manage_permission', 'Can assign permission'), ('can_change_own_record', 'Can change own records'), ('can_change_all_record', 'Can change all records'))},
        ),
        migrations.AddField(
            model_name='case',
            name='last_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='case_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 3, 13, 6, 38, 41, 77810, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['last_send'], 'permissions': (('can_view_all', 'Can view all cases'), ('can_view', 'Can view'), ('can_select_client', 'Can select client'), ('can_assign', 'Can assign new permissions'), ('can_send_to_client', 'Can send text to client'), ('can_manage_permission', 'Can assign permission'), ('can_add_record', 'Can add record'), ('can_change_own_record', 'Can change own records'), ('can_change_all_record', 'Can change all records'))},
        ),
        migrations.AddField(
            model_name='case',
            name='deadline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_deadline', to='events.Event'),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['last_send'], 'permissions': (('can_view_all', 'Can view all cases'), ('can_view', 'Can view'), ('can_view_free', 'Can view free cases'), ('can_select_client', 'Can select client'), ('can_assign', 'Can assign new permissions'), ('can_send_to_client', 'Can send text to client'), ('can_manage_permission', 'Can assign permission'), ('can_add_record', 'Can add record'), ('can_change_own_record', 'Can change own records'), ('can_change_all_record', 'Can change all records'))},
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_client', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='case',
            name='deadline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_deadline', to='events.Event', verbose_name='Dead-line'),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_action',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last action'),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last send'),
        ),
        migrations.AlterField(
            model_name='case',
            name='letter_count',
            field=models.IntegerField(default=0, verbose_name='Letter count'),
        ),
        migrations.AlterField(
            model_name='case',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='case',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified on'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Subject'),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['last_send'], 'permissions': (('can_view_all', 'Can view all cases'), ('can_view', 'Can view'), ('can_select_client', 'Can select client'), ('can_assign', 'Can assign new permissions'), ('can_send_to_client', 'Can send text to client'), ('can_manage_permission', 'Can assign permission'), ('can_add_record', 'Can add record'), ('can_change_own_record', 'Can change own records'), ('can_change_all_record', 'Can change all records'))},
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('permissions', models.ManyToManyField(to=b'auth.Permission', verbose_name='Permissions')),
            ],
        ),
    ]
