# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'cases', '0028_auto_20151218_0036'), (b'cases', '0029_case_has_project'), (b'cases', '0030_case_close_perm'), (b'cases', '0031_auto_20170317_1927')]

    dependencies = [
        ('cases', '0027_case_last_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='has_project',
            field=models.BooleanField(default=False, verbose_name='Has project'),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['last_send'], 'permissions': (('can_view_all', 'Can view all cases'), ('can_view', 'Can view'), ('can_select_client', 'Can select client'), ('can_assign', 'Can assign new permissions'), ('can_send_to_client', 'Can send text to client'), ('can_manage_permission', 'Can assign permission'), ('can_add_record', 'Can add record'), ('can_change_own_record', 'Can change own records'), ('can_change_all_record', 'Can change all records'), ('can_close_case', 'Can close case'))},
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Numer sprawy'),
        ),
    ]
