# Generated by Django 1.11.21 on 2019-06-13 17:49
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("teryt", "0001_initial"), ("cases", "0034_auto_20180104_0436")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="jst",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teryt.JST",
                verbose_name="Unit of administrative division",
            ),
        )
    ]
