# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-15 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0035_case_jst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='jst',
        ),
    ]
