# Generated by Django 1.11.21 on 2019-06-15 13:54
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("cases", "0035_case_jst")]

    operations = [migrations.RemoveField(model_name="case", name="jst")]
