# Generated by Django 3.2.18 on 2023-04-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_alter_case_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteCaseProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Cases to delete',
                'verbose_name_plural': 'Cases to delete',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cases.case',),
        ),
    ]
