# Generated by Django 4.2.11 on 2024-03-22 15:31

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0040_deletecaseproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=model_utils.fields.StatusField(choices=[('0', 'free'), ('3', 'moderated'), ('1', 'assigned'), ('2', 'closed')], default='0', max_length=100, no_check_for_status=True),
        ),
    ]
