# Generated by Django 5.2.13 on 2026-04-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0043_add_send_old_cases_reminder_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="advice_classification_request_sent_on",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Advice classification request sent on",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="advice_classification_response_status",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Advice classification response status",
            ),
        ),
    ]
