# Generated by Django 5.2.16 on 2026-08-10 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0003_n8ncasetagsrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="n8ncasetagsrequest",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Accepted at"
            ),
        ),
        migrations.AddField(
            model_name="n8ncasetagsrequest",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_ai_tags_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Accepted by",
            ),
        ),
        migrations.AddField(
            model_name="n8ncasetagsrequest",
            name="rejected_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Rejected at"
            ),
        ),
        migrations.AddField(
            model_name="n8ncasetagsrequest",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_ai_tags_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rejected by",
            ),
        ),
        migrations.AddField(
            model_name="n8ncasetagsrequest",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Rejection reason"),
        ),
    ]
