# Generated by Django 1.11.21 on 2019-06-13 17:43
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [("teryt_tree", "0004_auto_20170712_2335")]

    operations = [
        migrations.CreateModel(
            name="JST",
            fields=[],
            options={"proxy": True, "indexes": []},
            bases=("teryt_tree.jednostkaadministracyjna",),
        )
    ]
