# Generated by Django 5.2.12 on 2026-03-16 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celery_monitor", "0002_seed_monitor_periodic_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSlaSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "probe_name",
                    models.CharField(default="default", max_length=100, unique=True),
                ),
                (
                    "queue_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warn", "Warning"),
                            ("crit", "Critical"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("enqueued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lag_ms", models.IntegerField(default=0)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "worker_hostname",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("details_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
