# Generated by Django 1.9.12 on 2016-12-08 08:02
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("advicer", "0013_auto_20151218_0035")]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "verbose_name": "Problem regarding the right to information",
                "verbose_name_plural": "Problems regarding the right to information",
            },
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={
                "verbose_name": "The thematic scope of the request",
                "verbose_name_plural": "Thematic scopes of requests",
            },
        ),
        migrations.AlterModelOptions(
            name="personkind",
            options={
                "verbose_name": "Type of person who reporting the advice",
                "verbose_name_plural": "Types of people who report to for advice",
            },
        ),
        migrations.AddField(
            model_name="advice",
            name="helped",
            field=models.NullBooleanField(verbose_name="We helped?"),
        ),
        migrations.AlterField(
            model_name="advice",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advicer.Area",
                verbose_name="Problem regarding the right to information",
            ),
        ),
        migrations.AlterField(
            model_name="advice",
            name="institution_kind",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advicer.InstitutionKind",
                verbose_name="Institution kind",
            ),
        ),
        migrations.AlterField(
            model_name="advice",
            name="issues",
            field=models.ManyToManyField(
                blank=True,
                to="advicer.Issue",
                verbose_name="Thematic scopes of requests",
            ),
        ),
        migrations.AlterField(
            model_name="advice",
            name="person_kind",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advicer.PersonKind",
                verbose_name="Type of person who reporting the advice",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="institutionkind",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="personkind",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
