# Generated by Django 1.11.21 on 2019-06-15 13:54
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("teryt", "0001_initial"), ("advicer", "0017_auto_20190404_0337")]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="jst",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teryt.JST",
                verbose_name="Unit of administrative division",
            ),
        )
    ]
