
# Generated by Django 1.11.21 on 2019-06-27 09:34
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advicer', '0018_advice_jst'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice',
            options={'ordering': ['-created_on'], 'permissions': (('can_view_all_advices', 'Can view all advices'),), 'verbose_name': 'Advice', 'verbose_name_plural': 'Advices'},
        ),
    ]
