# Generated by Django 1.11.21 on 2019-07-07 21:27
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("advicer", "0019_auto_20190627_1134")]

    operations = [
        migrations.AlterField(
            model_name="advice",
            name="area",
            field=models.ManyToManyField(
                blank=True,
                to="advicer.Area",
                verbose_name="Problems regarding the right to information",
            ),
        )
    ]
