# Generated by Django 5.2.13 on 2026-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advicer", "0022_alter_advice_helped"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="area",
            name="tag_helper",
            field=models.TextField(
                blank=True,
                help_text="Helper text how to apply the tag.",
                null=True,
                verbose_name="Tag helper",
            ),
        ),
        migrations.AddField(
            model_name="institutionkind",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="institutionkind",
            name="tag_helper",
            field=models.TextField(
                blank=True,
                help_text="Helper text how to apply the tag.",
                null=True,
                verbose_name="Tag helper",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="issue",
            name="tag_helper",
            field=models.TextField(
                blank=True,
                help_text="Helper text how to apply the tag.",
                null=True,
                verbose_name="Tag helper",
            ),
        ),
        migrations.AddField(
            model_name="personkind",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="personkind",
            name="tag_helper",
            field=models.TextField(
                blank=True,
                help_text="Helper text how to apply the tag.",
                null=True,
                verbose_name="Tag helper",
            ),
        ),
    ]
