# Generated by Django 5.2.13 on 2026-04-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advicer", "0023_area_active_area_tag_helper_institutionkind_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advice",
            options={
                "ordering": ["-created_on"],
                "permissions": (("can_view_all_advices", "Can view all advices"),),
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
