# Generated by Django 5.2.15 on 2026-07-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advicer", "0027_area_is_local_government_issue_is_local_government"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="ai_assistant_tags",
            field=models.JSONField(
                blank=True,
                help_text="Tags generated by AI assistant",
                null=True,
                verbose_name="AI assistant tags",
            ),
        ),
    ]
