# Generated by Django 5.2.15 on 2026-07-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advicer', '0028_advice_ai_assistant_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag subject'),
        ),
    ]
