# Generated by Django 5.2.15 on 2026-07-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advicer', '0029_alter_advice_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
