# Generated by Django 5.2.16 on 2026-08-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advicer", "0030_remove_attachment"),
        ("ai_assistant", "0004_n8ncasetagsrequest_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="ai_tags_request",
            field=models.ForeignKey(
                blank=True,
                help_text="The AI request that produced the currently stored AI suggestion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advices",
                to="ai_assistant.n8ncasetagsrequest",
                verbose_name="AI tags request",
            ),
        ),
    ]
