# Generated by Django 5.2.17 on 2026-09-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advicer", "0031_advice_ai_tags_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="is_slapp",
            field=models.BooleanField(default=False, verbose_name="Is SLAPP area?"),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_slapp",
            field=models.BooleanField(default=False, verbose_name="Is SLAPP issue?"),
        ),
    ]
