# Generated by Django 5.2.17 on 2026-09-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advicer", "0032_area_is_slapp_issue_is_slapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="is_scope_def",
            field=models.BooleanField(
                default=False, verbose_name="Is scope definition issue?"
            ),
        ),
    ]
