# Generated by Django 5.2.17 on 2026-09-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advicer", "0033_issue_is_scope_def"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"verbose_name": "Area", "verbose_name_plural": "Areas"},
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={"verbose_name": "Issue", "verbose_name_plural": "Issues"},
        ),
        migrations.AlterField(
            model_name="advice",
            name="area",
            field=models.ManyToManyField(
                blank=True, to="advicer.area", verbose_name="Areas"
            ),
        ),
        migrations.AlterField(
            model_name="advice",
            name="issues",
            field=models.ManyToManyField(
                blank=True, to="advicer.issue", verbose_name="Issues"
            ),
        ),
    ]
