# Generated by Django 5.2.17 on 2026-09-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advicer", "0034_alter_area_options_alter_issue_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "tag_helper",
                    models.TextField(
                        blank=True,
                        help_text="Helper text how to apply the tag.",
                        null=True,
                        verbose_name="Tag helper",
                    ),
                ),
                (
                    "is_dip",
                    models.BooleanField(default=True, verbose_name="Is FOI issue?"),
                ),
                (
                    "is_local_government",
                    models.BooleanField(
                        default=False, verbose_name="Is local government issue?"
                    ),
                ),
                (
                    "is_slapp",
                    models.BooleanField(default=False, verbose_name="Is SLAPP issue?"),
                ),
                (
                    "is_out_of_scope",
                    models.BooleanField(default=False, verbose_name="Is Out of scope?"),
                ),
            ],
            options={
                "verbose_name": "Scope",
                "verbose_name_plural": "Scopes",
            },
        ),
        migrations.RemoveField(
            model_name="issue",
            name="is_scope_def",
        ),
    ]
