# Generated by Django 5.2.17 on 2026-09-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advicer", "0035_scope_remove_issue_is_scope_def"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionkind",
            name="is_undefined",
            field=models.BooleanField(default=False, verbose_name="Is undefined?"),
        ),
        migrations.AddField(
            model_name="personkind",
            name="is_undefined",
            field=models.BooleanField(default=False, verbose_name="Is undefined?"),
        ),
    ]
